### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by n0madic**

### CODE REVIEW

**Comment by xperimental** [comment]
@n0madic Sorry, I did not see your open pull-request up until now.

In my opinion the short forms of the flags do not make so much sense as they are not some standard flags that are used across multiple tools (for example like `-v` for verbose) but you still have to check what each short form of a long flag is. Would you be fine with taking them out again?

I have not tried out your change yet, I'll get to that soon.

**Comment by n0madic** [comment]
I needed only to hide good site requests from the log, short flags were made because of laziness to type the full arguments :)

**Comment by xperimental** [comment]
How about renaming the flags to `quiet` ("only show errors") and `verbose` ("show all requests including skipped")? That way there would be established short forms as well...

**Comment by n0madic** [comment]
Good options

**Comment by xperimental** [comment]
Generally verbose and quiet are mutually exclusive, which is not the case in your implementation. I can set both quiet and verbose and then get a mix of output. I'd probably solve this by having a "output level" variable that has three states "normal", "quiet" and "verbose" which then controls which things are output.

Thinking about this, it is probably easier to do that by just using a logging library, but this is spiraling a bit out of control in the context of your PR and so should probably be done later.

That said, can you still do the "mutually exclusive" part of the two options?

**Comment by n0madic** [comment]
By [current logic](https://github.com/n0madic/linky/blob/9c811032b2e1f39d86f8a31b373c5a9a41ce7885/supervisor.go#L91), the verbose mode has a higher priority over the others.
Pflag does not seem to have a functional with mutually exclusive flags. You can either make one verbose flag with different levels of detail or leave it alone and hope for the prudence of the user ...

**Comment by n0madic** [comment]
I would have made such levels of output messages

Flags | Details
------------ | -------------
without -v | display only errors
-v | normal mode (with 200s)
-vv | the most detailed mode

**Comment by xperimental** [comment]
I must have temporarily forgot how short-circuiting works, thanks for reminding me. Thanks for the contribution!

**Pull request merged**
